name: simple_counter
description: A simple counter application built using Flutter and Cubit for state management. The app increments and decrements a numeric value displayed on the screen.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^0.2.0

flutter:
  uses-material-design: true